/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\ti\simplelink_cc2640r2_sdk_3_30_00_20\source\ti\blestack\blelib\ctrlll\cc2640_ctrlll_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_3_30_00_20\source\ti\blestack\blelib\ctrlhci\cc2640_ctrlhci_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_3_30_00_20\source\ti\blestack\blelib\hci_tl\cc26xx_hci_tl_none.a"
"C:\ti\simplelink_cc2640r2_sdk_3_30_00_20\source\ti\blestack\blelib\host\cc26xx_att_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_3_30_00_20\source\ti\blestack\blelib\host\cc26xx_gap_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_3_30_00_20\source\ti\blestack\blelib\host\cc26xx_gatt_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_3_30_00_20\source\ti\blestack\blelib\host\cc26xx_l2cap_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_3_30_00_20\source\ti\blestack\blelib\host\cc26xx_profiles_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_3_30_00_20\source\ti\blestack\blelib\host\cc26xx_smp_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_3_30_00_20\source\ti\blestack\blelib\host\cc26xx_sm_xxbx.a"
